In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('students_data_logical.csv')

In [3]:
df.sample

<bound method NDFrame.sample of     cgpa   iq  placement
0    9.0  104          0
1    8.8  140          0
2    7.2  132          0
3    8.5  121          0
4    7.5  126          0
..   ...  ...        ...
95   9.5  125          0
96   7.5  116          0
97   6.6  136          0
98   6.0  104          0
99   5.3  133          0

[100 rows x 3 columns]>

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cgpa       100 non-null    float64
 1   iq         100 non-null    int64
 2   placement  100 non-null    int64
dtypes: float64(1), int64(2)
memory usage: 2.5 KB

In [5]:
df.isnull().sum()

cgpa         0
iq           0
placement    0
dtype: int64

In [6]:
df.isnull().sum()

cgpa         0
iq           0
placement    0
dtype: int64

In [7]:
df.shape

(100, 3)

In [8]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib.backends.registry'

In [ ]:
plt.scatter(df['cgpa'],df['iq'])

In [ ]:
plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

In [9]:
df1=pd.read_csv('students_data_logical.csv')

In [10]:
df1.shape

(100, 3)

In [11]:
df1.head()

   cgpa   iq  placement
0   9.0  104          0
1   8.8  140          0
2   7.2  132          0
3   8.5  121          0
4   7.5  126          0

In [ ]:
plt.scatter(df1['cgpa'],df1['iq'])

In [ ]:
plt.scatter(df1['cgpa'],df1['iq'],c=df1['placement'])

In [13]:
X=df1.iloc[ : ,0:2]   # independant Varible
Y=df1.iloc[ : ,-1]

In [14]:
X

    cgpa   iq
0    9.0  104
1    8.8  140
2    7.2  132
3    8.5  121
4    7.5  126
..   ...  ...
95   9.5  125
96   7.5  116
97   6.6  136
98   6.0  104
99   5.3  133

[100 rows x 2 columns]

In [15]:
Y

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Name: placement, Length: 100, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [24]:
x_train

    cgpa   iq
84   6.0  148
68   5.7  121
87   8.2  100
93   8.4  112
72   5.6  115
..   ...  ...
35   8.3  132
23   7.2  113
45   7.9  129
1    8.8  140
17   8.1  114

[80 rows x 2 columns]

In [25]:
x_test

    cgpa   iq
63   9.2  113
46   5.5  101
26   7.7  112
34   5.8  145
79   9.4  148
49   9.1  111
67   6.7  149
28   8.9  115
64   8.6  104
25   6.0  135
42   9.4  131
39   7.6  141
85   7.5  131
76   7.9  144
86   7.0  137
55   9.2  114
20   6.8  149
11   6.2  108
32   8.9  120
13   5.6  143

In [26]:
y_train

84    0
68    0
87    1
93    1
72    1
     ..
35    0
23    0
45    0
1     0
17    0
Name: placement, Length: 80, dtype: int64

In [27]:
y_test.shape

(20,)

In [28]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train=scaler.fit_transform(x_train)

In [29]:
x_train

array([[-9.52255694e-01,  1.47107206e+00],
       [-1.18264014e+00, -4.22560628e-01],
       [ 7.37230214e-01, -1.89538605e+00],
       [ 8.90819842e-01, -1.05377153e+00],
       [-1.25943495e+00, -8.43367893e-01],
       [-3.37897182e-01,  1.47107206e+00],
       [-1.02905051e+00, -1.61484788e+00],
       [-1.64340902e+00,  9.80130254e-01],
       [ 1.35158873e+00, -1.61484788e+00],
       [ 1.42838354e+00,  6.99592077e-01],
       [-7.98666066e-01, -1.47457879e+00],
       [-8.75460880e-01, -8.43367893e-01],
       [ 8.14025028e-01, -7.18879077e-02],
       [-1.84307554e-01,  1.12039934e+00],
       [-1.56661421e+00, -9.83636981e-01],
       [ 5.83640586e-01,  1.33080297e+00],
       [ 1.22871702e-01, -1.42022452e-01],
       [ 1.73556280e+00, -1.42022452e-01],
       [ 7.37230214e-01,  1.12039934e+00],
       [-4.14691996e-01, -1.33430970e+00],
       [-8.75460880e-01, -1.40444425e+00],
       [-1.02905051e+00,  1.05026480e+00],
       [-1.72020383e+00, -4.22560628e-01],
       [-4.91486810e-01, -1.33430970e+00],
       [ 1.22871702e-01,  2.78784813e-01],
       [-1.64340902e+00, -1.61484788e+00],
       [-1.72020383e+00, -4.92695172e-01],
       [ 1.99666516e-01, -1.05377153e+00],
       [ 1.12120428e+00, -9.83636981e-01],
       [ 3.53256144e-01, -1.42022452e-01],
       [ 1.27479391e+00,  1.19053389e+00],
       [-9.52255694e-01, -1.61484788e+00],
       [ 1.99666516e-01, -7.18879077e-02],
       [ 7.37230214e-01, -7.18879077e-02],
       [ 3.53256144e-01,  2.78784813e-01],
       [-3.37897182e-01,  2.08650269e-01],
       [-7.21871252e-01,  1.61134115e+00],
       [ 1.58197317e+00,  4.89188445e-01],
       [-1.64340902e+00, -1.82525151e+00],
       [-6.45076438e-01,  1.54120661e+00],
       [ 1.04440947e+00,  9.80130254e-01],
       [-1.48981939e+00,  4.19053901e-01],
       [ 9.67614656e-01, -4.22560628e-01],
       [-7.98666066e-01,  4.19053901e-01],
       [ 1.27479391e+00,  1.47107206e+00],
       [-9.52255694e-01,  4.89188445e-01],
       [-4.14691996e-01,  1.19053389e+00],
       [ 1.58197317e+00,  1.33080297e+00],
       [-3.07179256e-02, -7.18879077e-02],
       [-1.25943495e+00, -1.75511697e+00],
       [ 1.58197317e+00, -7.03098805e-01],
       [ 1.42838354e+00,  9.09995710e-01],
       [-3.07179256e-02, -1.05377153e+00],
       [-7.98666066e-01,  1.19053389e+00],
       [ 4.30050958e-01,  1.26066843e+00],
       [ 1.99666516e-01, -7.73233349e-01],
       [-3.07179256e-02, -3.52426084e-01],
       [-1.18264014e+00,  6.83811805e-02],
       [ 1.42838354e+00,  4.89188445e-01],
       [ 8.14025028e-01,  9.09995710e-01],
       [ 1.50517835e+00, -1.12390607e+00],
       [-3.07179256e-02,  3.48919357e-01],
       [-2.61102368e-01,  2.78784813e-01],
       [-1.41302458e+00,  9.80130254e-01],
       [ 5.83640586e-01, -1.75336360e-03],
       [-1.33622976e+00, -1.75511697e+00],
       [-7.21871252e-01,  7.69726621e-01],
       [ 4.60768884e-02, -4.92695172e-01],
       [-1.10584532e+00,  1.19053389e+00],
       [ 8.14025028e-01,  4.19053901e-01],
       [-4.91486810e-01,  6.29457533e-01],
       [-1.07512740e-01, -3.52426084e-01],
       [ 8.90819842e-01,  4.89188445e-01],
       [ 1.12120428e+00,  4.89188445e-01],
       [ 1.27479391e+00,  1.26066843e+00],
       [ 8.14025028e-01,  3.48919357e-01],
       [-3.07179256e-02, -9.83636981e-01],
       [ 5.06845772e-01,  1.38515725e-01],
       [ 1.19799910e+00,  9.09995710e-01],
       [ 6.60435400e-01, -9.13502437e-01]])

In [30]:
x_test=scaler.transform(x_test)
x_test

array([[ 1.50517835, -0.98363698],
       [-1.33622976, -1.82525151],
       [ 0.35325614, -1.05377153],
       [-1.10584532,  1.26066843],
       [ 1.65876798,  1.47107206],
       [ 1.42838354, -1.12390607],
       [-0.414692  ,  1.54120661],
       [ 1.27479391, -0.84336789],
       [ 1.04440947, -1.61484788],
       [-0.95225569,  0.55932299],
       [ 1.65876798,  0.27878481],
       [ 0.27646133,  0.98013025],
       [ 0.19966652,  0.27878481],
       [ 0.50684577,  1.19053389],
       [-0.18430755,  0.69959208],
       [ 1.50517835, -0.91350244],
       [-0.33789718,  1.54120661],
       [-0.79866607, -1.3343097 ],
       [ 1.27479391, -0.49269517],
       [-1.25943495,  1.12039934]])

In [31]:
# Training the Model using logistic Regression

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()

clf.fit(x_train,y_train)

LogisticRegression()

In [32]:
y_pred=clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
y_test

63    1
46    0
26    0
34    1
79    1
49    0
67    0
28    1
64    0
25    0
42    1
39    0
85    0
76    1
86    0
55    0
20    0
11    0
32    1
13    0
Name: placement, dtype: int64

In [34]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.7

In [35]:
import pickle
pickle.dump(clf,open('model.pkl','wb'))